// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/mtlprog/lore/internal/repository"
)

// MockAccountRepositoryer is an autogenerated mock type for the AccountRepositoryer type
type MockAccountRepositoryer struct {
	mock.Mock
}

type MockAccountRepositoryer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepositoryer) EXPECT() *MockAccountRepositoryer_Expecter {
	return &MockAccountRepositoryer_Expecter{mock: &_m.Mock}
}

// GetCompanies provides a mock function with given fields: ctx, limit, offset
func (_m *MockAccountRepositoryer) GetCompanies(ctx context.Context, limit int, offset int) ([]repository.CompanyRow, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanies")
	}

	var r0 []repository.CompanyRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repository.CompanyRow, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repository.CompanyRow); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CompanyRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepositoryer_GetCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanies'
type MockAccountRepositoryer_GetCompanies_Call struct {
	*mock.Call
}

// GetCompanies is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAccountRepositoryer_Expecter) GetCompanies(ctx interface{}, limit interface{}, offset interface{}) *MockAccountRepositoryer_GetCompanies_Call {
	return &MockAccountRepositoryer_GetCompanies_Call{Call: _e.mock.On("GetCompanies", ctx, limit, offset)}
}

func (_c *MockAccountRepositoryer_GetCompanies_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAccountRepositoryer_GetCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountRepositoryer_GetCompanies_Call) Return(_a0 []repository.CompanyRow, _a1 error) *MockAccountRepositoryer_GetCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepositoryer_GetCompanies_Call) RunAndReturn(run func(context.Context, int, int) ([]repository.CompanyRow, error)) *MockAccountRepositoryer_GetCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersons provides a mock function with given fields: ctx, limit, offset
func (_m *MockAccountRepositoryer) GetPersons(ctx context.Context, limit int, offset int) ([]repository.PersonRow, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPersons")
	}

	var r0 []repository.PersonRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repository.PersonRow, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repository.PersonRow); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PersonRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepositoryer_GetPersons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersons'
type MockAccountRepositoryer_GetPersons_Call struct {
	*mock.Call
}

// GetPersons is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAccountRepositoryer_Expecter) GetPersons(ctx interface{}, limit interface{}, offset interface{}) *MockAccountRepositoryer_GetPersons_Call {
	return &MockAccountRepositoryer_GetPersons_Call{Call: _e.mock.On("GetPersons", ctx, limit, offset)}
}

func (_c *MockAccountRepositoryer_GetPersons_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAccountRepositoryer_GetPersons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountRepositoryer_GetPersons_Call) Return(_a0 []repository.PersonRow, _a1 error) *MockAccountRepositoryer_GetPersons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepositoryer_GetPersons_Call) RunAndReturn(run func(context.Context, int, int) ([]repository.PersonRow, error)) *MockAccountRepositoryer_GetPersons_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockAccountRepositoryer) GetStats(ctx context.Context) (*repository.Stats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *repository.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*repository.Stats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *repository.Stats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepositoryer_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockAccountRepositoryer_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountRepositoryer_Expecter) GetStats(ctx interface{}) *MockAccountRepositoryer_GetStats_Call {
	return &MockAccountRepositoryer_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockAccountRepositoryer_GetStats_Call) Run(run func(ctx context.Context)) *MockAccountRepositoryer_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountRepositoryer_GetStats_Call) Return(_a0 *repository.Stats, _a1 error) *MockAccountRepositoryer_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepositoryer_GetStats_Call) RunAndReturn(run func(context.Context) (*repository.Stats, error)) *MockAccountRepositoryer_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepositoryer creates a new instance of MockAccountRepositoryer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepositoryer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepositoryer {
	mock := &MockAccountRepositoryer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
