// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mtlprog/lore/internal/model"
)

// MockStellarServicer is an autogenerated mock type for the StellarServicer type
type MockStellarServicer struct {
	mock.Mock
}

type MockStellarServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStellarServicer) EXPECT() *MockStellarServicer_Expecter {
	return &MockStellarServicer_Expecter{mock: &_m.Mock}
}

// FetchStellarToml provides a mock function with given fields: ctx, homeDomain
func (_m *MockStellarServicer) FetchStellarToml(ctx context.Context, homeDomain string) (*model.StellarTomlCurrency, string, error) {
	ret := _m.Called(ctx, homeDomain)

	if len(ret) == 0 {
		panic("no return value specified for FetchStellarToml")
	}

	var r0 *model.StellarTomlCurrency
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.StellarTomlCurrency, string, error)); ok {
		return rf(ctx, homeDomain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.StellarTomlCurrency); ok {
		r0 = rf(ctx, homeDomain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StellarTomlCurrency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, homeDomain)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, homeDomain)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStellarServicer_FetchStellarToml_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchStellarToml'
type MockStellarServicer_FetchStellarToml_Call struct {
	*mock.Call
}

// FetchStellarToml is a helper method to define mock.On call
//   - ctx context.Context
//   - homeDomain string
func (_e *MockStellarServicer_Expecter) FetchStellarToml(ctx interface{}, homeDomain interface{}) *MockStellarServicer_FetchStellarToml_Call {
	return &MockStellarServicer_FetchStellarToml_Call{Call: _e.mock.On("FetchStellarToml", ctx, homeDomain)}
}

func (_c *MockStellarServicer_FetchStellarToml_Call) Run(run func(ctx context.Context, homeDomain string)) *MockStellarServicer_FetchStellarToml_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStellarServicer_FetchStellarToml_Call) Return(_a0 *model.StellarTomlCurrency, _a1 string, _a2 error) *MockStellarServicer_FetchStellarToml_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStellarServicer_FetchStellarToml_Call) RunAndReturn(run func(context.Context, string) (*model.StellarTomlCurrency, string, error)) *MockStellarServicer_FetchStellarToml_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountDetail provides a mock function with given fields: ctx, accountID
func (_m *MockStellarServicer) GetAccountDetail(ctx context.Context, accountID string) (*model.AccountDetail, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountDetail")
	}

	var r0 *model.AccountDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AccountDetail, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AccountDetail); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccountDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetAccountDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountDetail'
type MockStellarServicer_GetAccountDetail_Call struct {
	*mock.Call
}

// GetAccountDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockStellarServicer_Expecter) GetAccountDetail(ctx interface{}, accountID interface{}) *MockStellarServicer_GetAccountDetail_Call {
	return &MockStellarServicer_GetAccountDetail_Call{Call: _e.mock.On("GetAccountDetail", ctx, accountID)}
}

func (_c *MockStellarServicer_GetAccountDetail_Call) Run(run func(ctx context.Context, accountID string)) *MockStellarServicer_GetAccountDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetAccountDetail_Call) Return(_a0 *model.AccountDetail, _a1 error) *MockStellarServicer_GetAccountDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetAccountDetail_Call) RunAndReturn(run func(context.Context, string) (*model.AccountDetail, error)) *MockStellarServicer_GetAccountDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountOperations provides a mock function with given fields: ctx, accountID, cursor, limit
func (_m *MockStellarServicer) GetAccountOperations(ctx context.Context, accountID string, cursor string, limit int) (*model.OperationsPage, error) {
	ret := _m.Called(ctx, accountID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountOperations")
	}

	var r0 *model.OperationsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*model.OperationsPage, error)); ok {
		return rf(ctx, accountID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *model.OperationsPage); ok {
		r0 = rf(ctx, accountID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OperationsPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, accountID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetAccountOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountOperations'
type MockStellarServicer_GetAccountOperations_Call struct {
	*mock.Call
}

// GetAccountOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - cursor string
//   - limit int
func (_e *MockStellarServicer_Expecter) GetAccountOperations(ctx interface{}, accountID interface{}, cursor interface{}, limit interface{}) *MockStellarServicer_GetAccountOperations_Call {
	return &MockStellarServicer_GetAccountOperations_Call{Call: _e.mock.On("GetAccountOperations", ctx, accountID, cursor, limit)}
}

func (_c *MockStellarServicer_GetAccountOperations_Call) Run(run func(ctx context.Context, accountID string, cursor string, limit int)) *MockStellarServicer_GetAccountOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockStellarServicer_GetAccountOperations_Call) Return(_a0 *model.OperationsPage, _a1 error) *MockStellarServicer_GetAccountOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetAccountOperations_Call) RunAndReturn(run func(context.Context, string, string, int) (*model.OperationsPage, error)) *MockStellarServicer_GetAccountOperations_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountSequence provides a mock function with given fields: ctx, accountID
func (_m *MockStellarServicer) GetAccountSequence(ctx context.Context, accountID string) (int64, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountSequence")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetAccountSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountSequence'
type MockStellarServicer_GetAccountSequence_Call struct {
	*mock.Call
}

// GetAccountSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockStellarServicer_Expecter) GetAccountSequence(ctx interface{}, accountID interface{}) *MockStellarServicer_GetAccountSequence_Call {
	return &MockStellarServicer_GetAccountSequence_Call{Call: _e.mock.On("GetAccountSequence", ctx, accountID)}
}

func (_c *MockStellarServicer_GetAccountSequence_Call) Run(run func(ctx context.Context, accountID string)) *MockStellarServicer_GetAccountSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetAccountSequence_Call) Return(_a0 int64, _a1 error) *MockStellarServicer_GetAccountSequence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetAccountSequence_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockStellarServicer_GetAccountSequence_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuerNFTMetadata provides a mock function with given fields: ctx, issuerID, assetCode
func (_m *MockStellarServicer) GetIssuerNFTMetadata(ctx context.Context, issuerID string, assetCode string) (*model.NFTMetadata, error) {
	ret := _m.Called(ctx, issuerID, assetCode)

	if len(ret) == 0 {
		panic("no return value specified for GetIssuerNFTMetadata")
	}

	var r0 *model.NFTMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.NFTMetadata, error)); ok {
		return rf(ctx, issuerID, assetCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.NFTMetadata); ok {
		r0 = rf(ctx, issuerID, assetCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NFTMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, issuerID, assetCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetIssuerNFTMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuerNFTMetadata'
type MockStellarServicer_GetIssuerNFTMetadata_Call struct {
	*mock.Call
}

// GetIssuerNFTMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - issuerID string
//   - assetCode string
func (_e *MockStellarServicer_Expecter) GetIssuerNFTMetadata(ctx interface{}, issuerID interface{}, assetCode interface{}) *MockStellarServicer_GetIssuerNFTMetadata_Call {
	return &MockStellarServicer_GetIssuerNFTMetadata_Call{Call: _e.mock.On("GetIssuerNFTMetadata", ctx, issuerID, assetCode)}
}

func (_c *MockStellarServicer_GetIssuerNFTMetadata_Call) Run(run func(ctx context.Context, issuerID string, assetCode string)) *MockStellarServicer_GetIssuerNFTMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetIssuerNFTMetadata_Call) Return(_a0 *model.NFTMetadata, _a1 error) *MockStellarServicer_GetIssuerNFTMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetIssuerNFTMetadata_Call) RunAndReturn(run func(context.Context, string, string) (*model.NFTMetadata, error)) *MockStellarServicer_GetIssuerNFTMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawAccountData provides a mock function with given fields: ctx, accountID
func (_m *MockStellarServicer) GetRawAccountData(ctx context.Context, accountID string) (map[string]string, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetRawAccountData")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetRawAccountData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawAccountData'
type MockStellarServicer_GetRawAccountData_Call struct {
	*mock.Call
}

// GetRawAccountData is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockStellarServicer_Expecter) GetRawAccountData(ctx interface{}, accountID interface{}) *MockStellarServicer_GetRawAccountData_Call {
	return &MockStellarServicer_GetRawAccountData_Call{Call: _e.mock.On("GetRawAccountData", ctx, accountID)}
}

func (_c *MockStellarServicer_GetRawAccountData_Call) Run(run func(ctx context.Context, accountID string)) *MockStellarServicer_GetRawAccountData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetRawAccountData_Call) Return(_a0 map[string]string, _a1 error) *MockStellarServicer_GetRawAccountData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetRawAccountData_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *MockStellarServicer_GetRawAccountData_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenDetail provides a mock function with given fields: ctx, code, issuer
func (_m *MockStellarServicer) GetTokenDetail(ctx context.Context, code string, issuer string) (*model.TokenDetail, error) {
	ret := _m.Called(ctx, code, issuer)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenDetail")
	}

	var r0 *model.TokenDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.TokenDetail, error)); ok {
		return rf(ctx, code, issuer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.TokenDetail); ok {
		r0 = rf(ctx, code, issuer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, issuer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetTokenDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenDetail'
type MockStellarServicer_GetTokenDetail_Call struct {
	*mock.Call
}

// GetTokenDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - issuer string
func (_e *MockStellarServicer_Expecter) GetTokenDetail(ctx interface{}, code interface{}, issuer interface{}) *MockStellarServicer_GetTokenDetail_Call {
	return &MockStellarServicer_GetTokenDetail_Call{Call: _e.mock.On("GetTokenDetail", ctx, code, issuer)}
}

func (_c *MockStellarServicer_GetTokenDetail_Call) Run(run func(ctx context.Context, code string, issuer string)) *MockStellarServicer_GetTokenDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetTokenDetail_Call) Return(_a0 *model.TokenDetail, _a1 error) *MockStellarServicer_GetTokenDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetTokenDetail_Call) RunAndReturn(run func(context.Context, string, string) (*model.TokenDetail, error)) *MockStellarServicer_GetTokenDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenOrderbook provides a mock function with given fields: ctx, code, issuer, limit
func (_m *MockStellarServicer) GetTokenOrderbook(ctx context.Context, code string, issuer string, limit int) (*model.TokenOrderbook, error) {
	ret := _m.Called(ctx, code, issuer, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenOrderbook")
	}

	var r0 *model.TokenOrderbook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*model.TokenOrderbook, error)); ok {
		return rf(ctx, code, issuer, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *model.TokenOrderbook); ok {
		r0 = rf(ctx, code, issuer, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenOrderbook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, code, issuer, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetTokenOrderbook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenOrderbook'
type MockStellarServicer_GetTokenOrderbook_Call struct {
	*mock.Call
}

// GetTokenOrderbook is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - issuer string
//   - limit int
func (_e *MockStellarServicer_Expecter) GetTokenOrderbook(ctx interface{}, code interface{}, issuer interface{}, limit interface{}) *MockStellarServicer_GetTokenOrderbook_Call {
	return &MockStellarServicer_GetTokenOrderbook_Call{Call: _e.mock.On("GetTokenOrderbook", ctx, code, issuer, limit)}
}

func (_c *MockStellarServicer_GetTokenOrderbook_Call) Run(run func(ctx context.Context, code string, issuer string, limit int)) *MockStellarServicer_GetTokenOrderbook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockStellarServicer_GetTokenOrderbook_Call) Return(_a0 *model.TokenOrderbook, _a1 error) *MockStellarServicer_GetTokenOrderbook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetTokenOrderbook_Call) RunAndReturn(run func(context.Context, string, string, int) (*model.TokenOrderbook, error)) *MockStellarServicer_GetTokenOrderbook_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionDetail provides a mock function with given fields: ctx, txHash
func (_m *MockStellarServicer) GetTransactionDetail(ctx context.Context, txHash string) (*model.Transaction, error) {
	ret := _m.Called(ctx, txHash)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionDetail")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Transaction, error)); ok {
		return rf(ctx, txHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = rf(ctx, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, txHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetTransactionDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionDetail'
type MockStellarServicer_GetTransactionDetail_Call struct {
	*mock.Call
}

// GetTransactionDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - txHash string
func (_e *MockStellarServicer_Expecter) GetTransactionDetail(ctx interface{}, txHash interface{}) *MockStellarServicer_GetTransactionDetail_Call {
	return &MockStellarServicer_GetTransactionDetail_Call{Call: _e.mock.On("GetTransactionDetail", ctx, txHash)}
}

func (_c *MockStellarServicer_GetTransactionDetail_Call) Run(run func(ctx context.Context, txHash string)) *MockStellarServicer_GetTransactionDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetTransactionDetail_Call) Return(_a0 *model.Transaction, _a1 error) *MockStellarServicer_GetTransactionDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetTransactionDetail_Call) RunAndReturn(run func(context.Context, string) (*model.Transaction, error)) *MockStellarServicer_GetTransactionDetail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStellarServicer creates a new instance of MockStellarServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStellarServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStellarServicer {
	mock := &MockStellarServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
