// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/mtlprog/lore/internal/repository"
)

// MockAccountQuerier is an autogenerated mock type for the AccountQuerier type
type MockAccountQuerier struct {
	mock.Mock
}

type MockAccountQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountQuerier) EXPECT() *MockAccountQuerier_Expecter {
	return &MockAccountQuerier_Expecter{mock: &_m.Mock}
}

// GetCorporate provides a mock function with given fields: ctx, limit, offset
func (_m *MockAccountQuerier) GetCorporate(ctx context.Context, limit int, offset int) ([]repository.CorporateRow, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCorporate")
	}

	var r0 []repository.CorporateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repository.CorporateRow, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repository.CorporateRow); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CorporateRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountQuerier_GetCorporate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCorporate'
type MockAccountQuerier_GetCorporate_Call struct {
	*mock.Call
}

// GetCorporate is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAccountQuerier_Expecter) GetCorporate(ctx interface{}, limit interface{}, offset interface{}) *MockAccountQuerier_GetCorporate_Call {
	return &MockAccountQuerier_GetCorporate_Call{Call: _e.mock.On("GetCorporate", ctx, limit, offset)}
}

func (_c *MockAccountQuerier_GetCorporate_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAccountQuerier_GetCorporate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountQuerier_GetCorporate_Call) Return(_a0 []repository.CorporateRow, _a1 error) *MockAccountQuerier_GetCorporate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountQuerier_GetCorporate_Call) RunAndReturn(run func(context.Context, int, int) ([]repository.CorporateRow, error)) *MockAccountQuerier_GetCorporate_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersons provides a mock function with given fields: ctx, limit, offset
func (_m *MockAccountQuerier) GetPersons(ctx context.Context, limit int, offset int) ([]repository.PersonRow, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPersons")
	}

	var r0 []repository.PersonRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]repository.PersonRow, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []repository.PersonRow); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PersonRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountQuerier_GetPersons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersons'
type MockAccountQuerier_GetPersons_Call struct {
	*mock.Call
}

// GetPersons is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAccountQuerier_Expecter) GetPersons(ctx interface{}, limit interface{}, offset interface{}) *MockAccountQuerier_GetPersons_Call {
	return &MockAccountQuerier_GetPersons_Call{Call: _e.mock.On("GetPersons", ctx, limit, offset)}
}

func (_c *MockAccountQuerier_GetPersons_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAccountQuerier_GetPersons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAccountQuerier_GetPersons_Call) Return(_a0 []repository.PersonRow, _a1 error) *MockAccountQuerier_GetPersons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountQuerier_GetPersons_Call) RunAndReturn(run func(context.Context, int, int) ([]repository.PersonRow, error)) *MockAccountQuerier_GetPersons_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *MockAccountQuerier) GetStats(ctx context.Context) (*repository.Stats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *repository.Stats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*repository.Stats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *repository.Stats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Stats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountQuerier_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockAccountQuerier_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountQuerier_Expecter) GetStats(ctx interface{}) *MockAccountQuerier_GetStats_Call {
	return &MockAccountQuerier_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockAccountQuerier_GetStats_Call) Run(run func(ctx context.Context)) *MockAccountQuerier_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountQuerier_GetStats_Call) Return(_a0 *repository.Stats, _a1 error) *MockAccountQuerier_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountQuerier_GetStats_Call) RunAndReturn(run func(context.Context) (*repository.Stats, error)) *MockAccountQuerier_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountQuerier creates a new instance of MockAccountQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountQuerier {
	mock := &MockAccountQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
