// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mtlprog/lore/internal/model"
)

// MockReputationQuerier is an autogenerated mock type for the ReputationQuerier type
type MockReputationQuerier struct {
	mock.Mock
}

type MockReputationQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReputationQuerier) EXPECT() *MockReputationQuerier_Expecter {
	return &MockReputationQuerier_Expecter{mock: &_m.Mock}
}

// GetGraph provides a mock function with given fields: ctx, accountID
func (_m *MockReputationQuerier) GetGraph(ctx context.Context, accountID string) (*model.ReputationGraph, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetGraph")
	}

	var r0 *model.ReputationGraph
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.ReputationGraph, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ReputationGraph); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReputationGraph)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReputationQuerier_GetGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraph'
type MockReputationQuerier_GetGraph_Call struct {
	*mock.Call
}

// GetGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockReputationQuerier_Expecter) GetGraph(ctx interface{}, accountID interface{}) *MockReputationQuerier_GetGraph_Call {
	return &MockReputationQuerier_GetGraph_Call{Call: _e.mock.On("GetGraph", ctx, accountID)}
}

func (_c *MockReputationQuerier_GetGraph_Call) Run(run func(ctx context.Context, accountID string)) *MockReputationQuerier_GetGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReputationQuerier_GetGraph_Call) Return(_a0 *model.ReputationGraph, _a1 error) *MockReputationQuerier_GetGraph_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReputationQuerier_GetGraph_Call) RunAndReturn(run func(context.Context, string) (*model.ReputationGraph, error)) *MockReputationQuerier_GetGraph_Call {
	_c.Call.Return(run)
	return _c
}

// GetScore provides a mock function with given fields: ctx, accountID
func (_m *MockReputationQuerier) GetScore(ctx context.Context, accountID string) (*model.ReputationScore, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetScore")
	}

	var r0 *model.ReputationScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.ReputationScore, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ReputationScore); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReputationScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReputationQuerier_GetScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScore'
type MockReputationQuerier_GetScore_Call struct {
	*mock.Call
}

// GetScore is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockReputationQuerier_Expecter) GetScore(ctx interface{}, accountID interface{}) *MockReputationQuerier_GetScore_Call {
	return &MockReputationQuerier_GetScore_Call{Call: _e.mock.On("GetScore", ctx, accountID)}
}

func (_c *MockReputationQuerier_GetScore_Call) Run(run func(ctx context.Context, accountID string)) *MockReputationQuerier_GetScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReputationQuerier_GetScore_Call) Return(_a0 *model.ReputationScore, _a1 error) *MockReputationQuerier_GetScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReputationQuerier_GetScore_Call) RunAndReturn(run func(context.Context, string) (*model.ReputationScore, error)) *MockReputationQuerier_GetScore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReputationQuerier creates a new instance of MockReputationQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReputationQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReputationQuerier {
	mock := &MockReputationQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
