// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mtlprog/lore/internal/model"
)

// MockStellarServicer is an autogenerated mock type for the StellarServicer type
type MockStellarServicer struct {
	mock.Mock
}

type MockStellarServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStellarServicer) EXPECT() *MockStellarServicer_Expecter {
	return &MockStellarServicer_Expecter{mock: &_m.Mock}
}

// GetAccountDetail provides a mock function with given fields: ctx, accountID
func (_m *MockStellarServicer) GetAccountDetail(ctx context.Context, accountID string) (*model.AccountDetail, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountDetail")
	}

	var r0 *model.AccountDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AccountDetail, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AccountDetail); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccountDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStellarServicer_GetAccountDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountDetail'
type MockStellarServicer_GetAccountDetail_Call struct {
	*mock.Call
}

// GetAccountDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockStellarServicer_Expecter) GetAccountDetail(ctx interface{}, accountID interface{}) *MockStellarServicer_GetAccountDetail_Call {
	return &MockStellarServicer_GetAccountDetail_Call{Call: _e.mock.On("GetAccountDetail", ctx, accountID)}
}

func (_c *MockStellarServicer_GetAccountDetail_Call) Run(run func(ctx context.Context, accountID string)) *MockStellarServicer_GetAccountDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStellarServicer_GetAccountDetail_Call) Return(_a0 *model.AccountDetail, _a1 error) *MockStellarServicer_GetAccountDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStellarServicer_GetAccountDetail_Call) RunAndReturn(run func(context.Context, string) (*model.AccountDetail, error)) *MockStellarServicer_GetAccountDetail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStellarServicer creates a new instance of MockStellarServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStellarServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStellarServicer {
	mock := &MockStellarServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
