with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/mtlprog/lore/internal/handler:
    interfaces:
      StellarServicer:
        config:
          dir: "internal/handler/mocks"
          outpkg: "mocks"
      AccountQuerier:
        config:
          dir: "internal/handler/mocks"
          outpkg: "mocks"
      TemplateRenderer:
        config:
          dir: "internal/handler/mocks"
          outpkg: "mocks"
